### PR TITLE
configure: use [ ] to compare values

### PR DESCRIPTION
**Pull request by amirouche**
ref: https://www.shellcheck.net/wiki/SC2283

### CODE REVIEW

**Comment by amirouche** [comment]
There is another error reported by shellcheck, I was not sure how to fix it.

That PR does not fix my problem, see https://github.com/egallesio/STklos/issues/427

**Comment by lassik** [comment]
Should probably be fixed in `configure.ac` and @egallesio can then re-run autoconf to fix `configure`.

**Comment by jpellegrini** [comment]
> Should probably be fixed in `configure.ac`

Good catch! I hadn't noticed the PR changed `configure` and not `configure.ac`. @amirouche would you like to change and force-push it?

**Comment by egallesio** [comment]
Hi @amirouche, 

Thanks for this PR. I have applied your patch in the `configure.ac`, since it will be used to rebuild the `configure` script. I have also changed the test with square brackets with an explicit call to "test" (just in case `configure` scripts runs on a machine without the symbolic link on `/bin/test`; this is very few unlikely now, but was current several years ago)

**Pull request merged**
