### PR TITLE
"equal?" arrays should have the same shape

### PR DESCRIPTION
**Pull request by jpellegrini**
Otherwise, we'd be considering 
```
[ a b c d ] 
```
the same as
```
[ a b ]
[ c d ]
```

### CODE REVIEW

**Comment by jpellegrini** [comment]
There is still a need for `array-equal?`, I think. I'll write more about it later.

**Comment by jpellegrini** [comment]
The added tests show why `array-equal?` is necessary.

```
a: [ -1 -2 -3 -4 -5 -6 -7 -8 ]
b: [ -1 -3 -5 -7 ]
c: share a, using only even indices
   c has addressable elements [ -1 -3 -5 -7 ], although it gets them jumping over a's data.
```

Now, `b` and `c` do _NOT_ have the same `ARRAY_DATA`. But they have the same addressable contents! So, they are not `equal?`, but `array-equal?` does see that and returns `#t`.

**Comment by jpellegrini** [comment]
`array-equal?` can still be optimized (it uses `array->list` on the shape, which is usually small -- we could avoid that)

**Comment by jpellegrini** [comment]
But doesn't it feel like `equal?` should do what `array-equal?` is doing?

**Comment by jpellegrini** [comment]
> Otherwise, we'd be considering

I mean, for consistency with `equal?` on lists: `(equal? '(a b c d)  '((a b) (c d)))` is false...

**Comment by egallesio** [comment]
`array-equal?` can still be optimized (it uses `array->list` on the shape, which is usually small -- we could avoid that)
Yep, but this probably not a problem in practice. 

> But doesn't it feel like `equal?` should do what `array-equal?` is doing?
> Otherwise, we'd be considering
> 
> I mean, for consistency with `equal?` on lists: `(equal? '(a b c d) '((a b) (c d)))` is false...

In fact, we can say that they are `array-equal?` if they print the same.  What do you think?

**Comment by jpellegrini** [comment]
> In fact, we can say that they are `array-equal?` if they print the same. What do you think?

I'm not sure we need two equality predicates. If they print the same, then they have the same shape and addressable contents. That would be what `equal?` checks...
If the arrays are shared or not, should we be dealing  with that?

**Comment by egallesio** [comment]
Hello @jpellegrini,

Ok for keeping only the `equal?` predicate for arrays. As a consequence, I have applied only the two first commits of this PR. I have not tried to make the `equal?` work for shared array. I let you do it in C as you kindly proposed :wink:
For now, I let this PR open.  

BTW, I have integrated your SRFI-25 documentation in the STklos ref. manual.
Thanks again for all.

**Comment by jpellegrini** [comment]
Hi @egallesio !

So, what I meant with my other message was this:

```
stklos> (define a (array (shape 0 8) -1 -2 -3 -4 -5 -6 -7 -8))
;; a
stklos> (define b (array (shape 0 4) -1 -3 -5 -7))
;; b
stklos> (define c (share-array a (shape 0 4) (lambda (x) (* x 2))))
;; c
stklos> b
#,(<array> (0 4) -1 -3 -5 -7)
stklos> c
#,(<array> (0 4) -1 -3 -5 -7)
stklos> (equal? b c)
#f
```

Shouldn't this be `#t`?

I have changed this PR so it does that. `test_equal_array` will fetch each element by its index (and not just traverse `ARRAY_DATA`), so now arrays that print the same would be `equal?`.
What do you think?

PS: I see you have added a release tag, but you did as if it was 1.60 being released? Wouldn't that be 1.70?
Also, maybe this change (array equality) could be included in 1.71, if 1.70 is released already? Or do you think the change is not good?

**Comment by jpellegrini** [comment]
Ops. Wait, something is not yet right.

**Comment by jpellegrini** [comment]
Ok, I think it's almost done, but I don't know why this happens:

```
(let ((a (array (shape 0 2 0 2 ) -1 -2 -3 -4)))
(equal? #,(<array> (1 3 1 3) -1 -2 -3 -4)
        (array-copy (share-array/origin  a 1 1))))
**** Error:
%equal-try: array index `0' < `1' for dimension `0'
```

`%equal-try` checks cycles, right? Why is it failing?

**Comment by jpellegrini** [comment]
> `%equal-try` checks cycles, right? Why is it failing?

Sorry, that was my mistake. It all seems to work now. I have included more tests for `equal?`

The only thing missing for SRFI-25 would be the share counter. It's not in the SRFI spec, but I thought it would be a nice addition. But it we don't get to make it work we can remove it...

(Although it would be rally nice to have the counter)

**Comment by egallesio** [comment]
> Sorry, that was my mistake. It all seems to work now. I have included more tests for equal?

No problem, but since the git history was not clear, I have not applied directly the PR but have  patched the files in `lib` and `tests` directories with your code.  Seems to be OK. 

Tests which uses array-copy to avoid previous behavior of `equal?` have been reverted to not use it anymore.

> PS: I see you have added a release tag, but you did as if it was 1.60 being released? Wouldn't that be 1.70?
Also, maybe this change (array equality) could be included in 1.71, if 1.70 is released already?

No I have added a release tag on 1.60 because someone asked me. 
1.70 is not ready yet :smile: 

Can we close this PR?

**Comment by egallesio** [comment]
OOPS. It seems that we have worked on the same file at the same time, and the last version of `srfi-25-impl.c` I have committed doesn't integrate your last version. I'll commit a new version in a couple of minutes.

**Comment by egallesio** [comment]
No files seems to be identical (some indentations only differ). Forge my previous message.

**Comment by jpellegrini** [comment]
> No files seem to be identical (some indentations only differ). Forget my previous message.

Are you working on merging it? Or would you like me to do that?

**Comment by egallesio** [comment]
> > No files seem to be identical (some indentations only differ). Forget my previous message.
> 
> Are you working on merging it? Or would you like me to do that?

I think that everything has been pushed now.  
Normally, the GitHub tree should be consistent with your tree (I hope so).

**Comment by jpellegrini** [comment]
That's great! It passes the tests, and now there's a progress indicator for SRFIs during the tests. :)

**Comment by egallesio** [comment]
> That's great! It passes the tests, and now there's a progress indicator for SRFIs during the tests. :)

Displaying this indicator was incorrect on Android. So it also permitted to spot a bug !

**Pull request closed without merging**
