### PR TITLE
Add SRFI-215: Central Log Exchange

### PR DESCRIPTION
**Pull request by jpellegrini**

### CODE REVIEW

**Comment by jpellegrini** [comment]
Hi @egallesio !
This one was merged into deflib, but was left out when you merged deflib into master...

**Comment by egallesio** [comment]
I don't know what I have done. Hope this is the only one.
Thanks, @jpellegrini, for your vigilance.

**Comment by jpellegrini** [comment]
Hi @egallesio !

It's STklos' 100th SRFI:

```
$ cat SUPPORTED-SRFIS |grep SRFI-|wc -l
100
```

:fireworks:

**Comment by egallesio** [comment]
We even have a key now for counting SRFIs with the `-V` option

```
$ stklos -V | grep count
(stklos.srfi.count 100)
```

**Pull request merged**
