### PR TITLE
Procedures optionally remember their sources (or something like that)

### PR DESCRIPTION
**Pull request by jpellegrini**
Hi @egallesio !
What do you think of this?
This patch does the same that was done to get docstrings and signatures in procedures.

```
stklos> (compiler:keep-source #t)
stklos> (define (f a b) (- a b))
;; f
stklos> (%procedure-source f)
(lambda (a b) (- a b))
```

For the future:

* Procedures do not remember their names when defined (not sure if it's worth implementing this).
* Code is not formatted. Maybe we can write a simple `stklos-source-format` procedure later.

### CODE REVIEW

**Comment by jpellegrini** [comment]
I added some basic tests now.

One thing: I've made `%procedure-source` return `#f` for non-procedures, because that's what `%procedure-arity`, `%procedure-doc` and `%procedure-signature` do. Should they instead trigger an error?

**Comment by jpellegrini** [comment]
Also included tests for `%procedure-arity`... And removed `(import STKLOS-COMPILER)` from the tests (they seem to run fine without it -- the parameter objects and procedures are visible in the STklos module anyway)

**Comment by jpellegrini** [comment]
Now I see there's `%procedure-name`... This could be used to show the procedure name with the source!

**Comment by egallesio** [comment]
Thanks for this PR @jpellegrini 

I have changed a bit the way things are represented to avoid the internal pointers in closure objects (since the source, as well as the signature are most of the time not used). So, source and signature are now stored in the procedure plist. 
Furthermore, the various compiler flags can be set now from the CLI (for stklos and stklos-compile commands).

**Pull request closed without merging**
