### PR TITLE
Add SRFI 236 - Evaluating expressions in an unspecified order

### PR DESCRIPTION
**Pull request by jpellegrini**
Hi @egallesio !
SRFI 236 went final, and since it's trivial, I've decided to make this PR. :)

The implementation I've included is different (and simpler) from the reference implementation: it just wraps the expressions in `begin`, but appending `(void)` as last expression.

### CODE REVIEW

**Comment by jpellegrini** [comment]
> The SRFI's sample implementation wraps them in `let` because `let` bindings are evaluated in arbitrary order. If STklos evaluates all `let` bindings in left-to-right order, the effect would be the same as `begin`.

Yes... Anyway, from the specification I understand that it can be implemented as `(begin ... (void))`. Or, without a `(void)` procedure, `(begin ... (if #f #t))`. The execution order will be the same as that of `begin`, but the SRFI doesn't forbid that.  :grin:  The extra work to execute in reverse order doesn't seem necessary...

**Comment by jpellegrini** [comment]
Now that I think of it... Since the SRFI says the result is "unspecified", and only requires that the results of the expressions are discarded, even this would fit:

```scheme
(define-syntax independently
      (syntax-rules ()
	((independently expr ...)
         (begin expr ... 'cool-symbol-returned-by-independently ))))
```
or:
```scheme
(define-syntax independently
      (syntax-rules ()
	((independently expr ...)
         (begin expr ... (random-integer) ))))
```
Because the result is "unspecified" (not specified by the SRFI)... Or did I miss something?

**Comment by jpellegrini** [comment]
Force-pushed to resolve a conflict...

**Comment by egallesio** [comment]
We can also shuffle the expressions of the `independently` to be sure that the user cannot know how evaluation will be done. Something like:

```scheme
(define-macro  (independently . body)
  (let ((shuffle (lambda (lst)
                   (map cdr
                        (sort (map (lambda (x) (cons (random-real) x)) lst)
                              (lambda (x y) (< (car x) (car y))))))))
    `(begin ,@(shuffle body) (void)))) 
```
```scheme

tklos> (define p display)
;; p
stklos> (independtly (p 1) (p 2) (p 3) (p 4))
2314stklos> (independtly (p 1) (p 2) (p 3) (p 4))
1234stklos> (independtly (p 1) (p 2) (p 3) (p 4))
1342stklos> 
```
:laughing:.

**Comment by lassik** [comment]
> Yes... Anyway, from the specification I understand that it can be implemented as `(begin ... (void))`. Or, without a `(void)` procedure, `(begin ... (if #f #t))`. The execution order will be the same as that of `begin`, but the SRFI doesn't forbid that. 😁

Yes.

> The extra work to execute in reverse order doesn't seem necessary...

The point of unspecified order is that compilers can sometimes optimize more things when they know they can change the order. (The other point is for documentation purposes.)

> Since the SRFI says the result is "unspecified", and only requires that the results of the expressions are discarded, even this would fit: [...]
> Because the result is "unspecified" (not specified by the SRFI)...

Yes, exactly. Many R7RS procedures return unspecified values and you could do the same for them.

> We can also shuffle the expressions of the independently to be sure that the user cannot know how evaluation will be done.

That's a fun idea :) And a valid implementation.

**Comment by jpellegrini** [comment]
So... Which version is better?
I think the shuffling one is really nice. If it's oK, I'll adapt the PR to include it (?)

**Comment by jpellegrini** [comment]
Hi @egallesio !
So... Why not use your shuffling implementation? :smile:   I've changed the PR to use it -- and also included a missing `provide`.

**Comment by egallesio** [comment]
Hi @jpellegrini, 
Merged.

**Pull request merged**
