### PR TITLE
More draft SRFIs

### PR DESCRIPTION
**Pull request by jpellegrini**
Just making the list complete...

### CODE REVIEW

**Comment by jpellegrini** [comment]
And SRFI-189 is (as of today) final! Changed that also.

**Comment by jpellegrini** [comment]
Github seems to be stuck checking mergeability of the PR... For several minues now!

It's certainyl not the commit -- it is only 6 lines.

**Comment by jpellegrini** [comment]
WIll close and open again...

**Comment by lassik** [comment]
Not sure if it's related, but the `master` branch does not build right now due to some problem with srfi-19.

**Pull request closed without merging**
