### PR TITLE
Add SRFI-151 - Bitwise Operations

### PR DESCRIPTION
**Pull request by jpellegrini**
Another one...

### CODE REVIEW

**Comment by lassik** [comment]
Great to have this. Of the several Scheme bitwise libraries, this is the one that is on track to be part of R7RS-large.

**Comment by jpellegrini** [comment]
Yes!
That's why I also proposed 41 (streams), 128 (comparators) and 143 (fixnums).
I'm planning to work on 130 (cursor-based string lib) and 159 (combinator formatting).

**Comment by lassik** [comment]
Great work! Thanks a lot for your contributions.

**Comment by egallesio** [comment]
Another great contribution. Thanks.
Merged!

**Pull request merged**
