### PR TITLE
Add non-mutable bindings in modules

### PR DESCRIPTION
**Pull request by jpellegrini**
Hi @egallesio !

About issue #335 ... I think this PR implements it.

I tried to not put more code in the VM, except for when the error is signaled (the module name is printed), so STklos won't get a slower `set!`. But `define` would need to check if the modules allows new bindings (should be very fast anyway).

The only part which seems a bit inefficient is that when we call `define`, it retrieves the old binding, if it exists, then makes it mutable again (if it was not), and that is a bit expensive. But I suppose people won't call global `define`s inside loops. :)

The commit message:

Adds the following primitives:

* `module-lock-define!`     disallows define in a module
* `module-define-allowed?`  checks if define is allowed

* `module-lock-binding!`    makes one binding non-mutable
* `module-lock-bindings!`  makes all module bindings non-mutable
* `binding-mutable?`        checks if a binding is mutable

The `SCHEME` module does not allow new bindings do be `DEFINE`d, and does not allow its bindings to be `SET!`, so it now can be safely used as a reference for the original Scheme bindings.

Update:
* Added a `define-constant` macro (it's trivial now)
* Added the module mutability info to `describe`

### CODE REVIEW

**Comment by jpellegrini** [comment]
* I'm not sure about the procedure names. Those were the best I could think of, but they still sound a bit strange. Tell me if you think of better names!

**Comment by jpellegrini** [comment]
I forgot: what about a description of the SCHEME module in the manual? In Chapter 3, "Program Structure"?

**Comment by jpellegrini** [comment]
Oops, there was a thinko in `env.c`, I corrected and force-pushed

**Comment by jpellegrini** [comment]
Hm, there is one problem: `define-constant` works for globals, but I didn't think of the situation when one would (wrongly?) use it locally.

**Comment by jpellegrini** [comment]
Yes, this needs a tiny bit more work:

```
stklos> (let ((b 2)) (define-constant c 4) (print c))
Received a SIGSGV signal.
```

**Comment by jpellegrini** [comment]
I have pushed another commit, and now there are no crashes anymore.
But `define-constant` only deals with globals. To make it work on local variables, probably we'd need to add a special form to the compiler.

Do I change its name to `module-define-constant`?

**Comment by egallesio** [comment]
Hi @jpellegrini, 

I have changed the way I have implemented things (more on that later).

**Comment by jpellegrini** [comment]
> I have changed the way I have implemented things (more on that later).

Ok @egallesio , it's great that it's implemented! :)

**Comment by egallesio** [comment]
I have added also `define-constant` on functions. You can do:

```scheme 
(define-constant (foo n) 
   (* n n))
```

**Pull request closed without merging**
