### PR TITLE
Add tests for SRFI-1

### PR DESCRIPTION
**Pull request by jpellegrini**
Not complete yet. These were adapted from Larceny to Chicken,
and now to STklos.

The Guile test suite is more complete, but also longer and it uses a different test framework; it would be harder to port.

### CODE REVIEW

**Comment by jpellegrini** [comment]
The tests will fail unless PR #135 is applied.

**Comment by jpellegrini** [comment]
This would fix #136

**Comment by egallesio** [comment]
**Thanks a lot** @jpellegrini for this port. It is probably sufficient to have this test set and add some tests from Guile if needed.

Merged.

**Comment by lassik** [comment]
https://github.com/srfi-explorations/srfi-test

**Comment by jpellegrini** [comment]
> https://github.com/srfi-explorations/srfi-test

That is great @lassik !
I'll work on a converter from SRFI-64 to STklos tests, and then we'll have all those tests available!

**Pull request merged**
