### PR TITLE
Use `~W` for general objects, not `~S`

### PR DESCRIPTION
**Pull request by jpellegrini**
Hi @egallesio !

Error messages do not know what the object is, so they shouldn't assume it's not circular:

```scheme
(define c (list 1 2 3 4))
(set-cdr! (cdddr c) (cdr c))
(+ c)
  => loops
```

### CODE REVIEW

**Comment by jpellegrini** [comment]
Maybe this also happens in other files. I just checked `number.c`...

**Comment by jpellegrini** [comment]
I have added patches for other files (not all of them)...

But I wonder if it wouldn't make sense to have a single directive, `~S`, that would already deal properly with circular structures?

**Comment by egallesio** [comment]
You are right @jpellegrini, 

I should have seen this. 

> But I wonder if it wouldn't make sense to have a single directive, `~S`, that would already deal properly with circular structures?

That would be probably a better solution. We could make `~S` and `~W` be equivalent in error messages. For errors, the format parsing is done in the specific function ` print_format` in file `src/error.c`.  This should be easier than passing on  all files (and when we have an error, the overhead implied by  `~W` doesn't matter).

**Comment by egallesio** [comment]
Hi @jpellegrini,
 I have modified the formatting function for errors. Now, both `~S` and `~W` use `write*` to print the culprit in an error message. 
Thanks for signaling the problem.
Since, it should resolve the problem, I close this PR, but you can reopen it, if needed.

**Comment by jpellegrini** [comment]
Great news! :smile:

**Pull request closed without merging**
