### PR TITLE
Add SRFI-215: Central Log Exchange

### PR DESCRIPTION
**Pull request by jpellegrini**
Hello @egallesio !

Trying to make sure we have enough SRFIs for STklos 1.70... :grin:

### CODE REVIEW

**Comment by egallesio** [comment]
> Trying to make sure we have enough SRFIs for STklos 1.70... ￼

We already have!

**Comment by jpellegrini** [comment]
OK, I think it's mergeable now.

**Comment by jpellegrini** [comment]
@egallesio this one seems to be small and with no problems (it's a simple Scheme program, and it's passing the tests).

**Comment by jpellegrini** [comment]
Closing - will reopen against deflib

**Pull request closed without merging**
